apiVersion: v2
name: cdviz-db
description: chart to manage cdviz-db (schema, data, functions,...)
type: application
version: 0.0.0 # version set during release
icon: https://cdviz.dev/assets/favicon.svg
keywords:
  - sdlc
  - cd
home: https://cdviz.dev/
sources:
  - https://github.com/cdviz-dev/cdviz
